language: python
python:
  - '3.5'
env:
  - DJANGO=1.9 DB=sqlite
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations
script:
  - python manage.py migrate -v 3
  - python manage.py test -v 3
